spring.application.name=e-commerce-web-jpa

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerce
spring.datasource.hikari.minimum-idle=1
spring.datasource.oracleucp.max-pool-size=5
spring.datasource.type=com.zaxxer.hikari.HikariDataSource

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# untuk bikin table database otomatis
spring.jpa.hibernate.ddl-auto=update 
